### ISSUE TITLE
*.com.mx 應為誤植

### ISSUE THREAD

**Issue by danny0838** [dallaslu/penzai-list#24]
.mx 為 Mexico 的語系碼，例如 https://apple.com.mx 會重導向到 https://www.apple.com/mx/ ，就像 https://apple.com.tw 會重導向到 https://www.apple.com/tw/ 一樣。不應該大範圍封鎖 *.com.mx。

**Comment by dallaslu** [comment]
應該是自動化腳本導致的問題。

**Comment by danny0838** [comment]
感謝處理，改了應該就沒問題了.reopen issue有什麼特別目的嗎？還是只是想確認？

**Comment by dallaslu** [comment]
我刪掉後腳本又自動加上了……
