### ISSUE TITLE
如何提交新的垃圾域名

### ISSUE THREAD

**Issue by yygcom** [dallaslu/penzai-list#5]
如何提交新的垃圾域名，发现还有很多漏网之鱼

**Comment by dallaslu** [comment]
直接创建 Pull requests

**Comment by xiaoxioamu** [comment]
换到 duckduckgo，或者 bing 吧，被污染的太严重了

**Comment by yygcom** [comment]
.shop2046.com
.101dh.com
.fjptnews.com
.uerelease.com
.xhscs.com
.88kka.com
.jysdzs.com
.jixian80.com
.788woool.com
.hb16888.com
.flamingows.com
.hnhbhy.com
.dqty888.com
.meshow100.com
.zyehouse.com
.dzgjy.com
.gzhaihang.com
.gvwusne.com
.liuhevet.com
.flamingows.com
.meirhome.com
.zhuhaiclub.com
.4000202123.com
.shimaozs.com
.quyn95.com
.ccqczzy.com
.xjnshj.com
.baicaisd.com
.hzwfwbac.com
.letaoshui.com
.yushu888.com
.09weixin.com
.gzzhuyuan.com
.ppp001.com
.jqljc.com
.lb060.com
.hzhanshu.com
.cf628.com
.hbysa.com
.shoeku.com
.igarden365.com
.zhlxyjxj.com
.goodvfx.com
.511soft.com
.ours2008.com
.tjhwmro.com
.xianzuoba6.com
.xptian.com
.syxygd168.com
.banquan3.com
.inkworker.com
.ht1008.com
.jiajiaxz.com
.jywlife.com
.yuechetuan.com
.esentl.com
.lunmm.com
.yccp85.com
.vtiorio.com
.czjdhx.com
.chechetun.com
.hoooeee.com
.9897sf.com
.azhahf.com
.mallarrow.com
.wxbgsj.com
.zhongjunch.com
.mstj120.com
.art0510.com
.whxdzs.com
.qwe1234.com
.xmydhsm.com
.scxtd56.com
.4r3r.com
.meixifenqi.com
.moshouhj.com
.kaifa.nlhjj.com
.jhtenglong.com
.jbw666.com
.yipinrong.com
.delinvip.com
.woaichaofl.com
.0gcm888.com
.daogoutuan.com
.7671117.com
.xtwlyy.com
.newerawire.com
.yatbdzsw.com
.bluebox3d.com
.58pla.com
.fenfenwo.com
.229cq.com
.760cf.com
.52dcr.com
.mwsoso.com
.xncftz.com
.tokyominer.com
.kcjcgs.com
.jiazhidi.com
.c1314c.com
.db5ds.com
.bubuzhe.com
.hgds688.com
.peigentea.com
.cdpywh.com
.kqunion.com
.sddpqycy.com
.lidemeifu.com
.jcpdw.com
.mouwuming.com
.hbttjgj.com
.magarfid.com
.zxitg.com
.wlylzxyy.com
.gujisc.com
.maximuum.com
.ahkdlyh.com
.88196833ox.com
